return {
    sensors = {
        {
            title = "CPU Vcore",
            kind = "voltage",
            unit = "V",
            path = "/sys/class/hwmon/hwmon2/in0_input",
            scale = 0.001,
            digits = 3,
            base = 1.05,
            warn_percent = 20,
            critical_percent = 25,
            order = 40
        },
        {
            title = "+5V",
            kind = "voltage",
            unit = "V",
            path = "/sys/class/hwmon/hwmon2/in1_input",
            scale = 0.005,
            digits = 2,
            base = 5.0,
            warn_percent = 5,
            critical_percent = 8,
            order = 60
        },
        {
            title = "+3.3V",
            kind = "voltage",
            unit = "V",
            path = "/sys/class/hwmon/hwmon2/in3_input",
            scale = 0.001,
            digits = 2,
            base = 3.3,
            warn_percent = 5,
            critical_percent = 8,
            order = 70
        },
        {
            title = "+12V",
            kind = "voltage",
            unit = "V",
            path = "/sys/class/hwmon/hwmon2/in4_input",
            scale = 0.012,
            digits = 2,
            base = 12.0,
            warn_percent = 5,
            critical_percent = 8,
            order = 50
        },
        {
            title = "PCH +1.0V",
            kind = "voltage",
            unit = "V",
            path = "/sys/class/hwmon/hwmon2/in9_input",
            scale = 0.001,
            digits = 3,
            base = 1.0,
            warn_percent = 5,
            critical_percent = 8,
            order = 50
        },
        {
            title = "CPU Temperature",
            kind = "temp",
            path = "/sys/class/hwmon/hwmon2/temp2_input",
            scale = 0.001,
            digits = 1,
            warn = 55,
            critical = 75,
            order = 10
        },
        {
            title = "PCH Temperature",
            kind = "temp",
            path = "/sys/class/hwmon/hwmon2/temp1_input",
            scale = 0.001,
            digits = 1,
            warn = 55,
            critical = 75,
            order = 30
        },
        {
            title = "CPU Fan Speed",
            kind = "fan",
            unit = "RPM",
            path = "/sys/class/hwmon/hwmon2/fan2_input",
            digits = 0,
            order = 20
        },
       --[[
         {
            title = "CHA Fan Speed",
            kind = "fan",
            unit = "RPM",
            path = "/sys/class/hwmon/hwmon2/fan1_input",
            digits = 0,
            order = 90
        }
        ]]
    }
}
